### ISSUE TITLE
An error occurred when run the test_tracker.

### ISSUE THREAD

**Issue by D-Walter** [djosix/PyDLSSVM#2]
i cant find the field named 'output' in the class tracker in file tracker.py.

**Comment by djosix** [comment]
Could you show me the error message?

`output` is yielded at this line:
https://github.com/djosix/PyDLSSVM/blob/master/dlssvm_tracker/tracker.py#L57

**Comment by D-Walter** [comment]
Interpreter shows message "'Tracker' object has no attribute 'outputs'" at [https://github.com/djosix/PyDLSSVM/blob/master/test_tracker.py#L77](url)

**Comment by djosix** [comment]
Thanks for your help :D
